### PR TITLE
Added photo with Bratislava

### PR DESCRIPTION
**Pull request by MatusModder**
I have pulled this image form Unplash and uploaded it to ImageGoNord.

### CODE REVIEW

**Comment by linuxdotexe** [comment]
Great picture! But please change the name to something more readable. If you used ImageGoNord, make sure the image name starts with "ign". This format, to be more specific:

`ign_imageName.png`

**Review by linuxdotexe — CHANGES_REQUESTED** [review]
Great picture! But please change the name to something more readable. If you used ImageGoNord, make sure the image name starts with "ign". This format, to be more specific:

`ign_imageName.png`

**Comment by theglitchh** [comment]
use a high pixelised image if you are going to use the filtering option or else it looks dotted

**Comment by linuxdotexe** [comment]
> use a high pixelised image if you are going to use the filtering option or else it looks dotted

YES!

**Comment by linuxdotexe** [comment]
Since it's been almost a month and no activity, I'm closing this PR. You can make the requested changes and always make another PR :)

**Pull request closed without merging**
